name: WordPress Plugin Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run WordPress Plugin Check
        uses: wordpress/plugin-check-action@98a1788320d0add90df2d8183934ecccbc4e05d2 # v1
        with:
          build-dir: "."
          slug: "prayerpop"
          categories: |
            general
            plugin_repo
            security
            performance
