name: WordPress Coding Standards

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run WPCS
        uses: 10up/wpcs-action@39f1a9eb6139795e6798d11b51eeecf5a9678ccc # stable
        with:
          standard: WordPress
          enable_warnings: true
          paths: "prayer-pop.php uninstall.php core src templates languages"
          excludes: "vendor node_modules .git .github"
